### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Hou-dev** [chaotic-aur/pkgbuild-chaotic-mirrorlist#2]
I am having a issue where I am building and installing the package but I do not have the chaotic-mirrorlist file in /etc/pacman.d 
I have to manually move the file to location when trying to install package.  
![image](https://user-images.githubusercontent.com/59487209/118386136-d1114500-b5da-11eb-83ab-085736bd72a0.png)

**Comment by PedroHLC** [comment]
The correct way to setup chaotic is:

1 - Install keyring:
```bash
cd /tmp
wget https://cdn-mirror.chaotic.cx/chaotic-aur/x86_64/chaotic-keyring-20210406-1-any.pkg.tar.zst
sudo pacman -U chaotic-keyring-20210406-1-any.pkg.tar.zst
# can't put link directly to pacman as that would try to check the keys that you don't own yet!
```

2 - Install mirrorlist:
```bash
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/x86_64/chaotic-mirrorlist-20210501-1-any.pkg.tar.zst'
```

3 - Add  `[chaotic-aur]` to `/etc/pacman.conf`, append to the end of the file:
```
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
```
